package permissions.dispatcher.processor.util;

import kotlin.Metadata;
/* compiled from: Constants.kt */
@Metadata(bv = {1, 0, 2}, d1 = {"\u0000\n\n\u0000\n\u0002\u0010\u000e\n\u0002\b\b\"\u000e\u0010\u0000\u001a\u00020\u0001X\u0086T¢\u0006\u0002\n\u0000\"\u000e\u0010\u0002\u001a\u00020\u0001X\u0086T¢\u0006\u0002\n\u0000\"\u000e\u0010\u0003\u001a\u00020\u0001X\u0086T¢\u0006\u0002\n\u0000\"\u000e\u0010\u0004\u001a\u00020\u0001X\u0086T¢\u0006\u0002\n\u0000\"\u000e\u0010\u0005\u001a\u00020\u0001X\u0086T¢\u0006\u0002\n\u0000\"\u000e\u0010\u0006\u001a\u00020\u0001X\u0086T¢\u0006\u0002\n\u0000\"\u000e\u0010\u0007\u001a\u00020\u0001X\u0086T¢\u0006\u0002\n\u0000\"\u000e\u0010\b\u001a\u00020\u0001X\u0086T¢\u0006\u0002\n\u0000¨\u0006\t"}, d2 = {"DEPRECATED_MESSAGE", "", "FILE_COMMENT", "GEN_CLASS_SUFFIX", "GEN_PENDING_PREFIX", "GEN_PERMISSION_PREFIX", "GEN_PERMISSION_REQUEST_SUFFIX", "GEN_REQUEST_CODE_PREFIX", "GEN_WITH_PERMISSION_CHECK_SUFFIX", "processor"}, k = 2, mv = {1, 1, 10})
/* loaded from: classes2.dex */
public final class ConstantsKt {
    public static final String DEPRECATED_MESSAGE = "android.app.Fragment was deprecated in Android P.";
    public static final String FILE_COMMENT = "This file was generated by PermissionsDispatcher. Do not modify!";
    public static final String GEN_CLASS_SUFFIX = "PermissionsDispatcher";
    public static final String GEN_PENDING_PREFIX = "PENDING_";
    public static final String GEN_PERMISSION_PREFIX = "PERMISSION_";
    public static final String GEN_PERMISSION_REQUEST_SUFFIX = "PermissionRequest";
    public static final String GEN_REQUEST_CODE_PREFIX = "REQUEST_";
    public static final String GEN_WITH_PERMISSION_CHECK_SUFFIX = "WithPermissionCheck";
}
